# Generated by Django 6.0.3 on 2026-04-03 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0002_question'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['section'], 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
    ]
