# Generated by Django 6.0.3 on 2026-04-05 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0005_alter_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='member_answer',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='member_answer'),
        ),
    ]
